added support for remote hddtemp

diff --git a/disk/check_disk_temp b/disk/check_disk_temp
--- a/disk/check_disk_temp
+++ b/disk/check_disk_temp
@@ -3,13 +3,16 @@
 CRITICAL=55
 WARNING=45
 STATS=0;
-
-while getopts 'hsc:w:' flag; do
+HOST="127.0.0.1"
+TIMEOUT=5
+while getopts 'hsc:w:H:t:' flag; do
   case "${flag}" in
     c) CRITICAL="${OPTARG}" ;;
     w) WARNING="${OPTARG}" ;;
     s) STATS=1;;
     h) HELP=1;;
+    H) HOST="${OPTARG}" ;;
+    t) TIMEOUT="${OPTARG}" ;;
   esac
 done
 
@@ -22,11 +25,14 @@ if [ $HELP ] ; then
   echo "  -h    This help page"
   echo "  -c    Returns a Critical error if temperature exceeds this value. Default:55"
   echo "  -w    Returns a Warning if temperature exceeds this value. Default:45"
+  echo " "
+  echo "  -H    which device to connect to, default 127.0.0.1"
   echo "  -s    Return statistics"
+  echo "  -t    Set the timeout, default 5 secibds"
   echo " "
   echo " "
   echo "Example"
-  echo "./check_disk_temp -c 55 -w 45 -s"
+  echo "./check_disk_temp -c 55 -w 45 -s -i 192.168.50.6 -t 4"
   exit 3;
 fi;
 
@@ -38,7 +44,14 @@ fi
 #nc 127.0.0.1 7634 |sed 's/|//m' | sed 's/||/ \n/g' | awk -F'|' '{print $1 ";" $3}'
 #exit 3;
 
-DRIVES=`nc 127.0.0.1 7634  < /dev/null |sed 's/|//m' | sed 's/||/ \n/g' | awk -F'|' '{print $1 ";" $3}'`
+HDDTEMP=`nc -w ${TIMEOUT} ${HOST} 7634  < /dev/null`
+
+if [ "$?" -gt "0" ]; then
+  echo "Failed to connect to hddtemp on ${HOST}";
+  exit 3;
+fi;
+
+DRIVES=`echo ${HDDTEMP} | sed 's/|//m' | sed 's/||/ \n/g' | awk -F'|' '{print $1 ";" $3}'`
 
 UNKNOWN=0;
 HOT=0;
@@ -46,6 +59,9 @@ WARM=0;
 OK=0
 TOTAL=0;
 SUM=0;
+
+MAX=0;
+MIN=1000;
 
 for DRIVE in $DRIVES; do
   IFS=';' read PATH TEMPERATURE <<< "$DRIVE"
@@ -65,25 +81,40 @@ for DRIVE in $DRIVES; do
   else
     OK=$(( $OK + 1 ));
   fi;
+
+  if [ "$TEMPERATURE" -lt "$MIN" ]; then
+    MIN=$TEMPERATURE
+  fi;
+
+  if [ "$TEMPERATURE" -gt "$MAX" ]; then
+    MAX=$TEMPERATURE
+  fi;
 done
 
-  AVERAGE=$(($SUM / $TOTAL))
-    
-  if [ "$HOT" -gt "0" ]; then
-    echo -n "Overheating average temperature is ${AVERAGE}C";
-    EXIT=2
-  elif [ "$WARM" -gt "0" ]; then
-    echo -n "To warm average temperature is ${AVERAGE}C";
-    EXIT=1;
-  else
-    echo -n "OK average temperature is ${AVERAGE}C";
-    EXIT=0;
-  fi;
+  
 
-  if [ "$STATS" -gt "0" ]; then
-    echo " | HOT=${HOT} WARM=${WARM} OK=${OK} UNKNOWN=${UNKNOWN} TOTAL=${TOTAL}";
-  else
-    echo "";
-  fi;
+if [ "$TOTAL" -lt "1" ]; then
+  echo -n "No Drives found";
+  exit 3;
+fi;
 
-  exit $EXIT;
+AVERAGE=$(($SUM / $TOTAL))
+
+if [ "$HOT" -gt "0" ]; then
+  echo -n "Overheating average temperature is ${AVERAGE}C";
+  EXIT=2
+elif [ "$WARM" -gt "0" ]; then
+  echo -n "To warm average temperature is ${AVERAGE}C";
+  EXIT=1;
+else
+  echo -n "OK average temperature is ${AVERAGE}C";
+  EXIT=0;
+fi;
+
+if [ "$STATS" -gt "0" ]; then
+  echo " | HOT=${HOT} WARM=${WARM} OK=${OK} UNKNOWN=${UNKNOWN} MAX=${MAX} MIN=${MIN} TOTAL=${TOTAL}";
+else
+  echo "";
+fi;
+
+exit $EXIT;
