bugfix: check_all_disks

diff --git a/disk/check_all_disks b/disk/check_all_disks
--- a/disk/check_all_disks
+++ b/disk/check_all_disks
@@ -6,18 +6,18 @@ WARNING=1
 
 while getopts 'hc:w:' flag; do
   case "${flag}" in
-    c) CRITICAL="${OPTARG}" ;;
-    w) WARNING="${OPTARG}" ;;
-    h) HELP=1 ;;
+  c) CRITICAL="${OPTARG}" ;;
+  w) WARNING="${OPTARG}" ;;
+  h) HELP=1 ;;
   esac
 done
 
-if [ $HELP ] ; then
+if [ $HELP ]; then
   echo "check_all_disks [OPTIONS...]"
-  echo "";
+  echo ""
   echo "Checks S.M.A.R.T values on all installed drives in the system"
-  echo "";
-  echo "Flags:";
+  echo ""
+  echo "Flags:"
   echo "  -h    This help page"
   echo "  -c    Returns a Critical error if more than this many drives are broken Default:2"
   echo "  -w    Returns a warning if more than this many drives are broken Default:1"
@@ -25,31 +25,38 @@ if [ $HELP ] ; then
   echo " "
   echo "Example"
   echo "./check_all_disks -c 2 -w 1"
-  exit 3;
-fi;
+  exit 3
+fi
 
-DRIVES=`sudo lshw -class disk | grep "logical name" | cut -d ":" -f2 | awk '{$1=$1};1'`
+DRIVES=$(lsblk --nodeps -n -o name,tran)
+
 TOTAL=0
 OK=0
 FAILED=0
-for DRIVE in $DRIVES; do
-  sudo /usr/lib64/nagios/plugins/check_ide_smart -q -d $DRIVE 
-  RESULT=$?
-  TOTAL=$((TOTAL + 1))
 
-  if [ "$RESULT" -eq "0" ]; then
-    OK=$((OK + 1))
+echo "$DRIVES" | (
+  while read -r DRIVE CONNECTION; do
+
+    if [ "$CONNECTION" == "sas" ] || [ "$CONNECTION" == "sata" ]; then
+      sudo /usr/lib64/nagios/plugins/check_ide_smart -q -d /dev/$DRIVE
+      RESULT=$?
+      TOTAL=$((TOTAL + 1))
+      if [ "$RESULT" -eq "0" ]; then
+        OK=$((OK + 1))
+      else
+        FAILED=$((FAILED + 1))
+      fi
+    fi
+
+  done
+
+  echo "${OK}/${TOTAL} DISKS ARE OK | TOTAL=${TOTAL} | OK=${OK} | FAILED=${FAILED}"
+
+  if [ $FAILED -ge $CRITICAL ]; then
+    exit 2
+  elif [ $FAILED -ge $WARNING ]; then
+    exit 1
   else
-    FAILED=$((FAILED + 1))
-  fi;
-done
-
-echo "${OK}/${TOTAL} DISKS ARE OK | TOTAL=${TOTAL} | OK=${OK} | FAILED=${FAILED}";
-
-if [ $FAILED -ge $CRITICAL ]; then
-  exit 2;
-elif [ $FAILED -ge $WARNING ]; then
-  exit 1;
-else
-  exit 0;
-fi;
+    exit 0
+  fi
+)
